[package]
name = "texteditor"
version = "0.1.0"
edition = "2024"

[dependencies]
shell-words = "1.1"
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
shlex = "1.3"
tempfile = "3"